### ISSUE TITLE
Iconfont not working

### ISSUE THREAD

**Issue by juanchristensen** [pixcai/next-antd-starter#1]
Hi,

While Antd and custom theming seem to be working, icons aren't.
I haven't been able to make them work.

If I add the `antd.min.css` file to the Head of the document, icons show up correctly, but the custom theme changes go back to the defaults.

Any clues?

<img width="55" alt="screen shot 2017-12-21 at 5 02 49 am" src="https://user-images.githubusercontent.com/860719/34246196-401664e6-e60c-11e7-9f65-43384a5bee02.png">
<img width="63" alt="screen shot 2017-12-21 at 5 03 01 am" src="https://user-images.githubusercontent.com/860719/34246197-404d256c-e60c-11e7-8c26-a04be4fcb09e.png">

**Comment by pixcai** [comment]
@juanchristensen Fixed

**Comment by juanchristensen** [comment]
Thanks! It's working perfectly now.
